// <auto-generated />
using System;
using Carnicerias.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carnicerias.Infrastructure.Migrations
{
    [DbContext(typeof(PlatformAccessDbContext))]
    [Migration("20261006153928_AddBranchInventoryAndSaleReservation")]
    partial class AddBranchInventoryAndSaleReservation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform_access")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carnicerias.Infrastructure.BranchInventoryBalance", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OnHand")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal>("Reserved")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.HasKey("CompanyId", "BranchId", "ProductId");

                    b.HasIndex("CompanyId", "ProductId");

                    b.ToTable("branch_inventory", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_branch_inventory_on_hand_nonnegative", "\"OnHand\" >= 0");

                            t.HasCheckConstraint("CK_branch_inventory_reserved_range", "\"Reserved\" >= 0 AND \"Reserved\" <= \"OnHand\"");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.BranchPriceList", b =>
                {
                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("BranchId", "PriceListId");

                    b.HasIndex("CompanyId", "PriceListId");

                    b.HasIndex("CompanyId", "BranchId", "IsActive");

                    b.ToTable("branch_price_lists", "catalog_pricing");
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.CatalogProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SaleMode")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "NormalizedCode")
                        .IsUnique();

                    b.HasIndex("CompanyId", "CategoryId", "IsActive");

                    b.ToTable("products", "catalog_pricing", t =>
                        {
                            t.HasCheckConstraint("CK_products_cost_positive", "\"Cost\" > 0");

                            t.HasCheckConstraint("CK_products_sale_mode", "\"SaleMode\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityDelta")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CompanyId", "ProductId");

                    b.HasIndex("CompanyId", "BranchId", "OperationId")
                        .IsUnique();

                    b.HasIndex("CompanyId", "BranchId", "ProductId", "CreatedAtUtc");

                    b.ToTable("inventory_movements", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_inventory_movements_delta_nonzero", "\"QuantityDelta\" <> 0");

                            t.HasCheckConstraint("CK_inventory_movements_kind", "\"Kind\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.PriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.ToTable("price_lists", "catalog_pricing");
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("categories", "catalog_pricing");
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ProductCode", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "NormalizedCode");

                    b.HasIndex("CompanyId", "NormalizedCode")
                        .IsUnique();

                    b.HasIndex("CompanyId", "ProductId");

                    b.ToTable("product_codes", "catalog_pricing");
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CompanyId", "ProductId");

                    b.HasIndex("CompanyId", "PriceListId", "ProductId")
                        .IsUnique()
                        .HasFilter("\"EffectiveToUtc\" IS NULL");

                    b.HasIndex("CompanyId", "PriceListId", "ProductId", "EffectiveFromUtc")
                        .IsUnique();

                    b.ToTable("product_prices", "catalog_pricing", t =>
                        {
                            t.HasCheckConstraint("CK_product_prices_amount_positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_product_prices_effective_range", "\"EffectiveToUtc\" IS NULL OR \"EffectiveToUtc\" > \"EffectiveFromUtc\"");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.SaleDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("CompanyId", "Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CompanyId", "PriceListId");

                    b.HasIndex("CompanyId", "BranchId", "UserId")
                        .IsUnique();

                    b.ToTable("sale_drafts", "pos_sales");
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.SaleDraftLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("SaleDraftId")
                        .HasColumnType("uuid");

                    b.Property<int>("SaleMode")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("SaleDraftId");

                    b.HasIndex("CompanyId", "ProductId");

                    b.ToTable("sale_draft_lines", "pos_sales", t =>
                        {
                            t.HasCheckConstraint("CK_sale_draft_lines_price_positive", "\"UnitPrice\" > 0");

                            t.HasCheckConstraint("CK_sale_draft_lines_quantity_positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("branches", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("companies", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.PermissionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.RoleCapability", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.UserAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("CompanyId", "BranchId");

                    b.HasIndex("UserId", "RoleId", "CompanyId")
                        .IsUnique()
                        .HasFilter("\"BranchId\" IS NULL");

                    b.HasIndex("UserId", "RoleId", "CompanyId", "BranchId")
                        .IsUnique()
                        .HasFilter("\"BranchId\" IS NOT NULL");

                    b.ToTable("user_assignments", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique();

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("users", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("CompanyId", "BranchId");

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("sessions", "platform_access", t =>
                        {
                            t.HasCheckConstraint("CK_sessions_context_pair", "(\"CompanyId\" IS NULL AND \"BranchId\" IS NULL) OR (\"CompanyId\" IS NOT NULL AND \"BranchId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.BranchInventoryBalance", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CatalogProduct", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.BranchPriceList", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.PriceList", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "PriceListId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.CatalogProduct", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "CategoryId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.InventoryMovement", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CatalogProduct", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.PriceList", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ProductCategory", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ProductCode", b =>
                {
                    b.HasOne("Carnicerias.Infrastructure.CatalogProduct", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ProductPrice", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.PriceList", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "PriceListId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CatalogProduct", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.SaleDraft", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.PriceList", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "PriceListId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.SaleDraftLine", b =>
                {
                    b.HasOne("Carnicerias.Infrastructure.SaleDraft", null)
                        .WithMany("Lines")
                        .HasForeignKey("SaleDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CatalogProduct", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.Branch", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.RoleCapability", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.PermissionDefinition", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.UserAssignment", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.UserSession", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.SaleDraft", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
