// <auto-generated />
using System;
using Carnicerias.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carnicerias.Infrastructure.Migrations
{
    [DbContext(typeof(PlatformAccessDbContext))]
    [Migration("20261008204602_AddSaleCustomerSnapshot")]
    partial class AddSaleCustomerSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform_access")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carnicerias.Infrastructure.BarcodeProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<int>("WeightDecimals")
                        .HasColumnType("integer");

                    b.Property<string>("WeightField")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "NormalizedName", "Revision")
                        .IsUnique();

                    b.ToTable("barcode_profiles", "inventory");
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.BranchInventoryBalance", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OnHand")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal>("Reserved")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.HasKey("CompanyId", "BranchId", "ProductId");

                    b.HasIndex("CompanyId", "ProductId");

                    b.ToTable("branch_inventory", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_branch_inventory_on_hand_nonnegative", "\"OnHand\" >= 0");

                            t.HasCheckConstraint("CK_branch_inventory_reserved_range", "\"Reserved\" >= 0 AND \"Reserved\" <= \"OnHand\"");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.BranchPriceList", b =>
                {
                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("BranchId", "PriceListId");

                    b.HasIndex("CompanyId", "PriceListId");

                    b.HasIndex("CompanyId", "BranchId", "IsActive");

                    b.ToTable("branch_price_lists", "catalog_pricing");
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.CashLedgerMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountDelta")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CashierShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PosTerminalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.HasIndex("CompanyId", "CashierShiftId");

                    b.HasIndex("CompanyId", "CreatedAtUtc");

                    b.HasIndex("CompanyId", "SaleId");

                    b.HasIndex("CashierShiftId", "Method", "CreatedAtUtc");

                    b.HasIndex("CompanyId", "BranchId", "OperationId")
                        .IsUnique();

                    b.HasIndex("CompanyId", "BranchId", "PosTerminalId", "CreatedAtUtc");

                    b.ToTable("cash_ledger", "payments_cash", t =>
                        {
                            t.HasCheckConstraint("CK_cash_ledger_amount_nonzero", "\"AmountDelta\" <> 0");

                            t.HasCheckConstraint("CK_cash_ledger_kind", "\"Kind\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.CashierShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OpeningCash")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid?>("PosTerminalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.HasIndex("CompanyId", "OpenedAtUtc");

                    b.HasIndex("CompanyId", "BranchId", "CashierId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("CompanyId", "BranchId", "PosTerminalId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0 AND \"PosTerminalId\" IS NOT NULL");

                    b.HasIndex("CompanyId", "BranchId", "PosTerminalId", "OpenedAtUtc");

                    b.ToTable("cashier_shifts", "payments_cash", t =>
                        {
                            t.HasCheckConstraint("CK_cashier_shifts_opening_cash_nonnegative", "\"OpeningCash\" >= 0");

                            t.HasCheckConstraint("CK_cashier_shifts_status", "\"Status\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.CatalogProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SaleMode")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "NormalizedCode")
                        .IsUnique();

                    b.HasIndex("CompanyId", "CategoryId", "IsActive");

                    b.ToTable("products", "catalog_pricing", t =>
                        {
                            t.HasCheckConstraint("CK_products_cost_positive", "\"Cost\" > 0");

                            t.HasCheckConstraint("CK_products_sale_mode", "\"SaleMode\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ConfirmedSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccountChargeAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CashierShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PaymentRequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("PosTerminalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceDraftId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.HasIndex("CompanyId", "CashierShiftId");

                    b.HasIndex("CompanyId", "ConfirmedAtUtc");

                    b.HasIndex("CompanyId", "CustomerId");

                    b.HasIndex("CompanyId", "PriceListId");

                    b.HasIndex("CompanyId", "SourceDraftId")
                        .IsUnique();

                    b.HasIndex("CompanyId", "BranchId", "PosTerminalId", "ConfirmedAtUtc");

                    b.ToTable("confirmed_sales", "pos_sales", t =>
                        {
                            t.HasCheckConstraint("CK_confirmed_sales_account_charge", "\"AccountChargeAmount\" >= 0 AND \"AccountChargeAmount\" <= \"Total\" AND (\"AccountChargeAmount\" = 0 OR (\"CustomerId\" IS NOT NULL AND \"CustomerCode\" IS NOT NULL AND \"CustomerName\" IS NOT NULL))");

                            t.HasCheckConstraint("CK_confirmed_sales_total_positive", "\"Total\" > 0");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ConfirmedSaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InventoryPieceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("PieceIdentifier")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<int>("SaleMode")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryPieceId")
                        .IsUnique()
                        .HasFilter("\"InventoryPieceId\" IS NOT NULL");

                    b.HasIndex("SaleId");

                    b.HasIndex("CompanyId", "ProductId");

                    b.ToTable("confirmed_sale_lines", "pos_sales", t =>
                        {
                            t.HasCheckConstraint("CK_confirmed_sale_lines_quantity_positive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_confirmed_sale_lines_unit_price_positive", "\"UnitPrice\" > 0");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.CustomerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CreditEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Name");

                    b.HasIndex("CompanyId", "NormalizedCode")
                        .IsUnique();

                    b.ToTable("customers", "customers_credit");
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.CustomerSaleCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CashierShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.HasIndex("SaleId")
                        .IsUnique();

                    b.HasIndex("CompanyId", "BranchId");

                    b.HasIndex("CompanyId", "CashierShiftId");

                    b.HasIndex("CompanyId", "SaleId");

                    b.HasIndex("CompanyId", "CustomerId", "CreatedAtUtc");

                    b.ToTable("sale_charges", "customers_credit", t =>
                        {
                            t.HasCheckConstraint("CK_sale_charges_amount_positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityDelta")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CompanyId", "CreatedAtUtc");

                    b.HasIndex("CompanyId", "ProductId");

                    b.HasIndex("CompanyId", "BranchId", "CreatedAtUtc");

                    b.HasIndex("CompanyId", "BranchId", "OperationId")
                        .IsUnique();

                    b.HasIndex("CompanyId", "BranchId", "ProductId", "CreatedAtUtc");

                    b.ToTable("inventory_movements", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_inventory_movements_delta_nonzero", "\"QuantityDelta\" <> 0");

                            t.HasCheckConstraint("CK_inventory_movements_kind", "\"Kind\" IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.InventoryPiece", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarcodeProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalIdentifier")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("IdentifierField")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("InventoryMovementId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedSourceSystem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawBarcode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReceivedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ReceivedWeightKg")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeProfileId");

                    b.HasIndex("InventoryMovementId");

                    b.HasIndex("ReceivedByUserId");

                    b.HasIndex("CompanyId", "ProductId");

                    b.HasIndex("CompanyId", "BranchId", "OperationId")
                        .IsUnique();

                    b.HasIndex("CompanyId", "NormalizedSourceSystem", "ExternalIdentifier")
                        .IsUnique();

                    b.HasIndex("CompanyId", "BranchId", "ProductId", "ReceivedAtUtc");

                    b.ToTable("pieces", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_pieces_received_weight_positive", "\"ReceivedWeightKg\" > 0");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.PosTerminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CredentialHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHistorical")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("CredentialHash")
                        .IsUnique()
                        .HasFilter("\"CredentialHash\" IS NOT NULL");

                    b.HasIndex("CompanyId", "BranchId", "Name")
                        .IsUnique();

                    b.ToTable("pos_terminals", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.PriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("price_lists", "catalog_pricing");
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("categories", "catalog_pricing");
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ProductCode", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("ProductId", "NormalizedCode");

                    b.HasIndex("CompanyId", "NormalizedCode")
                        .IsUnique();

                    b.HasIndex("CompanyId", "ProductId");

                    b.ToTable("product_codes", "catalog_pricing");
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CompanyId", "ProductId");

                    b.HasIndex("CompanyId", "PriceListId", "ProductId")
                        .IsUnique()
                        .HasFilter("\"EffectiveToUtc\" IS NULL");

                    b.HasIndex("CompanyId", "PriceListId", "ProductId", "EffectiveFromUtc")
                        .IsUnique();

                    b.ToTable("product_prices", "catalog_pricing", t =>
                        {
                            t.HasCheckConstraint("CK_product_prices_amount_positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_product_prices_effective_range", "\"EffectiveToUtc\" IS NULL OR \"EffectiveToUtc\" > \"EffectiveFromUtc\"");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.SaleDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CashierShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConfirmedSaleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PosTerminalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TicketSlot")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("CompanyId", "CashierShiftId");

                    b.HasIndex("CompanyId", "PriceListId");

                    b.HasIndex("CompanyId", "BranchId", "PosTerminalId");

                    b.HasIndex("CompanyId", "BranchId", "UserId", "TicketSlot")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("sale_drafts", "pos_sales");
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.SaleDraftLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InventoryPieceId")
                        .HasColumnType("uuid");

                    b.Property<string>("PieceIdentifier")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("SaleDraftId")
                        .HasColumnType("uuid");

                    b.Property<int>("SaleMode")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryPieceId");

                    b.HasIndex("SaleDraftId");

                    b.HasIndex("CompanyId", "ProductId");

                    b.ToTable("sale_draft_lines", "pos_sales", t =>
                        {
                            t.HasCheckConstraint("CK_sale_draft_lines_price_positive", "\"UnitPrice\" > 0");

                            t.HasCheckConstraint("CK_sale_draft_lines_quantity_positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.SalePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AppliedAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TenderedAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("sale_payments", "payments_cash", t =>
                        {
                            t.HasCheckConstraint("CK_sale_payments_applied_positive", "\"AppliedAmount\" > 0");

                            t.HasCheckConstraint("CK_sale_payments_tendered_positive", "\"TenderedAmount\" > 0");
                        });
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("branches", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("companies", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.PermissionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.RoleCapability", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.UserAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("CompanyId", "BranchId");

                    b.HasIndex("UserId", "RoleId", "CompanyId")
                        .IsUnique()
                        .HasFilter("\"BranchId\" IS NULL");

                    b.HasIndex("UserId", "RoleId", "CompanyId", "BranchId")
                        .IsUnique()
                        .HasFilter("\"BranchId\" IS NOT NULL");

                    b.ToTable("user_assignments", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique();

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("users", "platform_access");
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PosTerminalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PosTerminalId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("CompanyId", "BranchId");

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("sessions", "platform_access", t =>
                        {
                            t.HasCheckConstraint("CK_sessions_context_pair", "(\"CompanyId\" IS NULL AND \"BranchId\" IS NULL) OR (\"CompanyId\" IS NOT NULL AND \"BranchId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.BarcodeProfile", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.BranchInventoryBalance", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CatalogProduct", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.BranchPriceList", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.PriceList", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "PriceListId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.CashLedgerMovement", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CashierShift", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "CashierShiftId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.ConfirmedSale", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "SaleId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Carnicerias.Infrastructure.PosTerminal", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId", "PosTerminalId")
                        .HasPrincipalKey("CompanyId", "BranchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.CashierShift", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.PosTerminal", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId", "PosTerminalId")
                        .HasPrincipalKey("CompanyId", "BranchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.CatalogProduct", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "CategoryId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ConfirmedSale", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CashierShift", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "CashierShiftId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "CustomerId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Carnicerias.Infrastructure.PriceList", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "PriceListId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.SaleDraft", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "SourceDraftId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.PosTerminal", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId", "PosTerminalId")
                        .HasPrincipalKey("CompanyId", "BranchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ConfirmedSaleLine", b =>
                {
                    b.HasOne("Carnicerias.Infrastructure.InventoryPiece", null)
                        .WithMany()
                        .HasForeignKey("InventoryPieceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Carnicerias.Infrastructure.ConfirmedSale", null)
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CatalogProduct", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.CustomerAccount", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.CustomerSaleCharge", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CashierShift", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "CashierShiftId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "CustomerId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.ConfirmedSale", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "SaleId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.InventoryMovement", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CatalogProduct", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.InventoryPiece", b =>
                {
                    b.HasOne("Carnicerias.Infrastructure.BarcodeProfile", null)
                        .WithMany()
                        .HasForeignKey("BarcodeProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.InventoryMovement", null)
                        .WithMany()
                        .HasForeignKey("InventoryMovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CatalogProduct", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.PosTerminal", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.PriceList", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ProductCategory", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ProductCode", b =>
                {
                    b.HasOne("Carnicerias.Infrastructure.CatalogProduct", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ProductPrice", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.PriceList", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "PriceListId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CatalogProduct", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.SaleDraft", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CashierShift", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "CashierShiftId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Carnicerias.Infrastructure.PriceList", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "PriceListId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.PosTerminal", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId", "PosTerminalId")
                        .HasPrincipalKey("CompanyId", "BranchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.SaleDraftLine", b =>
                {
                    b.HasOne("Carnicerias.Infrastructure.InventoryPiece", null)
                        .WithMany()
                        .HasForeignKey("InventoryPieceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Carnicerias.Infrastructure.SaleDraft", null)
                        .WithMany("Lines")
                        .HasForeignKey("SaleDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carnicerias.Infrastructure.CatalogProduct", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.SalePayment", b =>
                {
                    b.HasOne("Carnicerias.Infrastructure.ConfirmedSale", null)
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.Branch", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.RoleCapability", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.PermissionDefinition", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.UserAssignment", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Carnicerias.PlatformAccess.UserSession", b =>
                {
                    b.HasOne("Carnicerias.PlatformAccess.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Carnicerias.Infrastructure.PosTerminal", null)
                        .WithMany()
                        .HasForeignKey("PosTerminalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Carnicerias.PlatformAccess.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carnicerias.PlatformAccess.Branch", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "BranchId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.ConfirmedSale", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Carnicerias.Infrastructure.SaleDraft", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
